name: Build APK for Android

on:
  push: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.11" }

    - name: System deps
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk zip unzip lib32stdc++6

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install --user "setuptools<70" cython buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Buildozer سيقبل الرخص تلقائياً لأننا أضفنا
    # android.accept_sdk_license = True في buildozer.spec
    - name: Build APK
      env:
        P4A_ACCEPT_SDK_LICENSE: "y"
      run: buildozer android debug

    - uses: actions/upload-artifact@v4
      with:
        name: SSHServer-APK
        path: bin/*.apk
