name: Build APK for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk zip unzip lib32stdc++6

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install --user "setuptools<70" cython buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Accept Android SDK licenses
      run: yes | $ANDROIDSDK/tools/bin/sdkmanager --licenses || true
      env:
        ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk

    - name: Build APK
      env:
        P4A_ACCEPT_SDK_LICENSE: "y"
        ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SSHServer-APK
        path: bin/*.apk
